### ISSUE TITLE
when can spago be in nixpkgs?

### ISSUE THREAD

**Issue by shmish111** [justinwoo/easy-purescript-nix#49]

**Comment by shmish111** [comment]
We just upgraded to PS 0.12 with spago, psc-package etc and there's quite a few things we need to get outside of nixpkgs which makes things messy, spago being one of them. It would be really nice if it were in nixpkgs.

**Comment by justinwoo** [comment]
maybe it can go in there, just take spago.nix and modify it for nixpkgs and PR it. i'd appreciate if you left a comment attributing the work, like with the purescript derivation in nixpkgs.

**Comment by justinwoo** [comment]
example: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/purescript/purescript/default.nix

**Comment by rubenmoor** [comment]
I find `spago` version 0.15.3 in `nixos unstable` now.

Unfortunately it doesn't seem to work. When I do `spago init` and `spago build`, I get

    [warn] Unable to parse compiler and package set versions, not checking if `purs` is compatible with it..
    [info] Installation complete.                           
    /bin/sh: /home/ruben/.nix-profile/bin/purs: No such file or directory
    [error] Failed to build.

**Comment by justinwoo** [comment]
okay so, looks like there is now a spago derivation defined in terms of haskell packages on nixpkgs. see https://github.com/NixOS/nixpkgs/pull/90470/files#diff-ff69727980d21718eb6a6677f7dd9857

the definition of spago on nixpkgs thus has no relation to this project at all, and i ask that you report any issues elsewhere. sorry.

i'll also close this issue because it seems this isn't really necessary to track anymore, since the only other step to be performed, if at all, is to replace the all-packages spago with spago derivations derived from here.
